# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AC_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'AC_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x41\x43_service.proto\x12\x0e\x61irconditioner\"\xae\x01\n\x15\x41irConditionerControl\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05power\x18\x02 \x01(\x08\x12\x13\n\x0btemperature\x18\x03 \x01(\x05\x12\"\n\x04mode\x18\x04 \x01(\x0e\x32\x14.airconditioner.Mode\x12+\n\tfan_speed\x18\x05 \x01(\x0e\x32\x18.airconditioner.FanSpeed\x12\r\n\x05swing\x18\x06 \x01(\x08\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t*6\n\x04Mode\x12\x08\n\x04\x43OOL\x10\x00\x12\x08\n\x04HEAT\x10\x01\x12\x07\n\x03\x46\x41N\x10\x02\x12\x07\n\x03\x44RY\x10\x03\x12\x08\n\x04\x41UTO\x10\x04*8\n\x08\x46\x61nSpeed\x12\x07\n\x03LOW\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04HIGH\x10\x02\x12\r\n\tAUTOMATIC\x10\x03\x32\xc1\x01\n\x15\x41irConditionerService\x12M\n\nSetControl\x12%.airconditioner.AirConditionerControl\x1a\x18.airconditioner.Response\x12Y\n\tGetStatus\x12%.airconditioner.AirConditionerControl\x1a%.airconditioner.AirConditionerControlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AC_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODE']._serialized_start=242
  _globals['_MODE']._serialized_end=296
  _globals['_FANSPEED']._serialized_start=298
  _globals['_FANSPEED']._serialized_end=354
  _globals['_AIRCONDITIONERCONTROL']._serialized_start=37
  _globals['_AIRCONDITIONERCONTROL']._serialized_end=211
  _globals['_RESPONSE']._serialized_start=213
  _globals['_RESPONSE']._serialized_end=240
  _globals['_AIRCONDITIONERSERVICE']._serialized_start=357
  _globals['_AIRCONDITIONERSERVICE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
