# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lamp_service_pb2 as actuators_dot_lamp__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in actuators/lamp_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LampServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LigarLampada = channel.unary_unary(
                '/LampService/LigarLampada',
                request_serializer=actuators_dot_lamp__service__pb2.Empty.SerializeToString,
                response_deserializer=actuators_dot_lamp__service__pb2.Empty.FromString,
                _registered_method=True)
        self.DesligarLampada = channel.unary_unary(
                '/LampService/DesligarLampada',
                request_serializer=actuators_dot_lamp__service__pb2.Empty.SerializeToString,
                response_deserializer=actuators_dot_lamp__service__pb2.Empty.FromString,
                _registered_method=True)


class LampServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LigarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LampServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LigarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.LigarLampada,
                    request_deserializer=actuators_dot_lamp__service__pb2.Empty.FromString,
                    response_serializer=actuators_dot_lamp__service__pb2.Empty.SerializeToString,
            ),
            'DesligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.DesligarLampada,
                    request_deserializer=actuators_dot_lamp__service__pb2.Empty.FromString,
                    response_serializer=actuators_dot_lamp__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LampService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LampService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LampService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LigarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LampService/LigarLampada',
            actuators_dot_lamp__service__pb2.Empty.SerializeToString,
            actuators_dot_lamp__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LampService/DesligarLampada',
            actuators_dot_lamp__service__pb2.Empty.SerializeToString,
            actuators_dot_lamp__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
